packages:
  - apps/*
  - packages/*
  - scripts/*
catalog:
  zod: "^3.24.4"
  better-auth: "^1.2.8"
  autumn-js: "^0.0.36"
  superjson: "^2.2.2"
  "@trpc/server": "^11.1.2"
  "@trpc/client": "^11.1.2"
  "@trpc/tanstack-react-query": "^11.1.2"
  wrangler: "^4.16.0"
  typescript: "^5.8.3"
patchedDependencies:
  novel: patches/novel.patch